### ISSUE TITLE
why was node-mtp archived/deprecated?

### ISSUE THREAD

**Issue by mreinstein** [tidepool-org/webmtp#6]
Hello,

I was wondering about the motivation of archiving that repo and defering to this one. Is it _purely_ the desire for cross platform (windows) support? Were there other reasons?

On my mac, `node-mtp` seems to actually work, whereas `webmtp` just pauses indefinitely trying to get the filename when running the example nodejs snippet from this project's readme.

**Comment by gniezen** [comment]
Hi @mreinstein ! `node-mtp` was a simple wrapper around the `libmtp` library, which requires native code to run. We rewrote the MTP functions in JS so that we could also run it in the browser. `webmtp` will use WebUSB in the browser, and `node-usb` in Node.js. 

Would you mind trying out the `update-node-usb` branch to see if it resolves the issue you're experiencing?

**Comment by mreinstein** [comment]
Thanks for the clarification!

So if I'm targeting _only_ a platform that `node-mtp` supports (macos nodejs in my case) am I better served by that library? It seems like possibly a more performant/simpler integration to underlying mtp functionality.

It might be nice to add a blurb to the very top of `node-mtp`'s README indicating _why_ the project was archived.

**Comment by mreinstein** [comment]
since that repo is archived I'm unable to send any PRs but I'd suggest modifying the README to provide this extra color on _why_ node-mtp was deprecated. thanks for answering my questions on this!

**Comment by gniezen** [comment]
> So if I'm targeting only a platform that node-mtp supports (macos nodejs in my case) am I better served by that library? It seems like possibly a more performant/simpler integration to underlying mtp functionality.

`node-mtp` _should_ continue to work just fine if you're only targeting Node.js. However, I'd rather that you use `webmtp` instead, as that's the library we'll be supporting going forward. Did you get it to work, or is it still pausing while trying to get the filename?

> I'd suggest modifying the README to provide this extra color on why node-mtp was deprecated

Great suggestion, I've made the changes.

**Comment by mreinstein** [comment]
> you use webmtp instead, as that's the library we'll be supporting going forward

I get that, but it's also a more complicated strategy, involving implementing a big chunk of usb in js. I was hoping for something simpler and closer to the metal.


> Did you get it to work

I gave up when nether library was working as expected.

**Comment by gniezen** [comment]
> I gave up when nether library was working as expected.

I'm sorry to hear that. If you can give me more details on what went wrong (logs, device used etc.) I could try to help troubleshoot.

**Comment by mreinstein** [comment]
> I'm sorry to hear that

I didn't intend for that to sound like a failing of either library; I just wasn't getting the results I was after and ran out of time to explore this because it wasn't critical, more of a bonus feature. :) 

> If you can give me more details on what went wrong (logs, device used etc.) I could try to help troubleshoot.

Thanks! I really appreciate the offer. 👍   The `node-mtp` package works as advertised, but what is lacking in the `mtp.getFileListing()` call is any metadata on file creation time. (I need to get only the list of files that were created since some timestamp `x` so I can always get just the latest set of new files).

I will try to update to the `update-node-usb` branch as you described and see if that fixes the hanging problem I was encountering.

**Comment by gniezen** [comment]
> any metadata on file creation time. (I need to get only the list of files that were created since some timestamp x so I can always get just the latest set of new files).

Object handles increment chronologically, so if you sort them (e.g. `handles.sort((a, b) => b - a);`)  the most recent ones will be at the top. But yeah, getting the actual file creation time would be nice.

**Comment by mreinstein** [comment]
doesn't seem to work. my code:

```javascript
import Mtp from 'webmtp'
//import fs  from 'fs'


// need to find vendorId and productId, I did this on macos with:
//		ioreg -p IOUSB -l -b | grep -E "@|idVendor|idProduct"

const vendorId = 6353
const productId = 20194
const mtp = new Mtp(vendorId, productId)

mtp.addEventListener('error', err => console.log('Error', err))

mtp.addEventListener('ready', async () => {
	
	await mtp.openSession()
	const handles = await mtp.getObjectHandles()
	console.log('handles:', handles)
	const objectHandle = handles[0]
	console.log('getting filename for handle', objectHandle)
	const fileName = await mtp.getFileName(objectHandle)
	console.log('filename:', fileName.toString())
	
	//const array = await mtp.getFile(objectHandle, fileName)
	//fs.writeFileSync(fileName, array)

	//await mtp.close()
})
```

When I run this what I see:
```bash
handles: [
  7, 13, 11, 5, 14, 1,
  2, 12,  3, 8, 10, 6,
  9,  4
]
getting filename for handle 7
Getting file name with object handle 7
Sending ArrayBuffer {
  [Uint8Contents]: <14 00 00 00 01 00 03 98 02 00 00 00 07 00 00 00 07 dc 00 00>,
  byteLength: 20
}
```

this is pointing at my local copy of `webmtp` which I git pulled and then checked out the `update-node-usb` branch.

**Comment by mreinstein** [comment]
note: I'm running this on node 18.6.0 on macos

**Comment by gniezen** [comment]
Is it possible that the object does not have a filename? Maybe try reading the filenames of the other object handles?

Also, any chance that the device is using PTP instead of MTP? Can you share which device you're connecting to?

**Comment by mreinstein** [comment]
I've been using `File Transfer Mode` on a Google Pixel 3a

**Comment by gniezen** [comment]
File Transfer mode should be using MTP, yes.

I just tested the `update-node-usb` branch with a Fairphone 3 (Android 11) on Node 18.7.0 on MacOS 12.5.1 and it listed all the files without any issues.

Have you tried reading on of the other handles?

**Comment by mreinstein** [comment]
I've tried reading 5 other handles,  removing all other usb devices, removing android file transfer in the off chance it was interfering, tried node 16, nothing works. :(

**Comment by gniezen** [comment]
That's frustrating :( If `node-mtp` works for you, maybe just continue using that? I'm not planning on making updates to it - but if it works, there's no reason it should stop working.

**Comment by mreinstein** [comment]
> If node-mtp works for you, maybe just continue using that?

It does work for me, the only downside is there's no efficient way to query the creation timestamp for the media. In order to determine that for a given file I'd need to first transfer the whole file and then try to extract exif data from the binary. The existing `node-mtp` doesn't expose any file metadata stuff from the underlying libmtp.

Anyway I don't want to keep jamming more requests/asks in this closed ticket. It's not a big problem for me. I really appreciate all the time you've given me on this! ❤️
